//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckGoWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atc
    {
        public int AtcID { get; set; }
        public int VehicleID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public decimal Speed { get; set; }
        public string Altitude { get; set; }
        public string Accuracy { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Angle { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Vehicles Vehicles { get; set; }
    }
}
